name: johnson
favicon: null
layout_spectrum: 0.69374
typography_spectrum: 0.4283
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
title: 'This Life of Johnson | Simple Man'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#282828'
    - '#d8d5d0'
    - '#7e5c53'
    - '#9ba19f'
  brandStrength: 0.9375
  lightness: 0.6875
  saturation: 0.375
  rhythmicContrast: 0.75
purpose: []
