name: johnson
favicon: null
layout_spectrum: 0.4228753987699747
typography_spectrum: 0.5586960667278618
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.21234626229852438
  lightness: 0.6674993250053376
  saturation: 0.006380093516781926
  rhythmicContrast: 0.18211601884104311
purpose: []
